version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  postgres:
      image: postgres
      restart: always
#      volumes:
#        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: todos
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
      networks:
        - network-backend
networks:
  network-backend:

#volumes: 
#  postgres_data:
